version: 0.2

phases:
    pre_build:
        commands:
            - npm install
            - npm install -g ts-node
    build:
        commands:
            - npm run build

artifacts:
    files:
        - "**/*"
    discard-paths: no
    base-directory: ./
